# Generated by Django 5.2.6 on 2025-09-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weblog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="weblog",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="weblogs", to="weblog.tag"
            ),
        ),
    ]
