# Generated by Django 5.2.6 on 2025-10-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weblog", "0002_tag_weblog_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="weblog",
            options={
                "permissions": [
                    ("wiev_post_with_image", "Can view post including image")
                ]
            },
        ),
        migrations.AlterField(
            model_name="weblog",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="weblogs_tag", to="weblog.tag"
            ),
        ),
    ]
