# Generated by Django 5.2.6 on 2025-10-10 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("weblog", "0003_alter_weblog_options_alter_weblog_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="weblog",
            options={
                "permissions": [
                    ("wiev_weblog_with_image", "Can view weblog including image")
                ]
            },
        ),
    ]
