# Generated by Django 5.2.6 on 2025-10-11 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("weblog", "0004_alter_weblog_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="weblog",
            options={
                "permissions": [
                    ("view_weblog_with_image", "Can view weblog including image")
                ]
            },
        ),
    ]
